## @section Ingress parameters
##
ingress:
  ## @param ingress.enabled Enable or disable the ingress
  ##
  enabled: true
  ## @param ingress.className The class name for the ingress
  ##
  className: nginx
  ## @param ingress.clusterIssuerRef The cluster issuer reference for the ingress
  ##
  clusterIssuerRef: ""
  ## @param ingress.host The host for the ingress
  ##
  host: ""
  ## @param ingress.customDomain The custom domain for the ingress
  ##
  customDomain: ""

## @section CloudNativePG parameters
##
cnpg:
  ## @param cnpg.enabled Enable or disable CloudNativePG
  ##
  enabled: true
  ## @param cnpg.nameOverride Override the name of the CloudNativePG cluster
  ## Default: "{release-name}-postgresql"
  ##
  nameOverride: ""
  ## @param cnpg.instances Number of instances (1 for single, 2+ for high availability)
  ##
  instances: 1
  ## @param cnpg.imageName PostgreSQL image to use
  ##
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0
  storage:
    ## @param cnpg.storage.size Persistent volume size for each instance
    ##
    size: 8Gi
  ## @param cnpg.database Name of the CloudNativePG database to create
  ##
  database: nextcloud
  ## @param cnpg.owner Name of the database user
  ##
  owner: app

## @section Collabora Online parameters
##
collabora:
  ## @param collabora.enabled Enable or disable Collabora Online
  ##
  enabled: false
  ingress:
    ## @param collabora.ingress.enabled Enable or disable the ingress for Collabora
    ##
    enabled: true
    ## @param collabora.ingress.className The class name for the ingress
    ##
    className: "nginx"
    ## @param collabora.ingress.annotations Ingress annotations
    ##
    annotations: {}
    ## @param collabora.ingress.hosts[0].host Host for the ingress
    ##
    hosts:
      - host: "doc.nextcloud.knd.local"
        paths:
          ## @param collabora.ingress.hosts[0].paths[0].path Path for the ingress
          ##
          - path: /
            ## @param collabora.ingress.hosts[0].paths[0].pathType Path type for the ingress
            ##
            pathType: ImplementationSpecific
    aliasgroups:
      ## @param collabora.ingress.aliasgroups[0].host Alias group host
      ##
      - host: "http://nextcloud.knd.local:80"
    ## @param collabora.ingress.extra_params Extra parameters for Collabora
    ##
    extra_params: "--o:ssl.enable=false --o:ssl.termination=true"
  resources:
    limits:
      ## @param collabora.resources.limits.cpu CPU limit for Collabora
      ##
      cpu: "1800m"
      ## @param collabora.resources.limits.memory Memory limit for Collabora
      ##
      memory: "2000Mi"
    requests:
      ## @param collabora.resources.requests.cpu CPU request for Collabora
      ##
      cpu: "1800m"
      ## @param collabora.resources.requests.memory Memory request for Collabora
      ##
      memory: "2000Mi"

## @section Nextcloud parameters
##
## @param image The image for Nextcloud
##
image: ""
## @param imagePullPolicy Pull policy for Nextcloud image
##
imagePullPolicy: Always
## @param storageSize Set the storage size
##
storageSize: "40Gi"
## @param storageClassName Set the storage class
##
storageClassName: ""

## @section K8up parameters
##
k8up:
  ## @param k8up.enabled Enable or disable K8up
  ##
  enabled: false
  ## @param k8up.endpoint S3 endpoint
  ##
  endpoint: ""
  ## @param k8up.bucket S3 bucket name
  ##
  bucket: ""