{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-ingress
  annotations:
    {{- if .Values.ingress.clusterIssuerRef }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuerRef }}
    {{- end }}
    {{- if eq .Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "128M"
    {{- end }}
spec:
  ingressClassName: {{.Values.ingress.className }}
  {{- if .Values.ingress.clusterIssuerRef }}
  tls:
    - hosts:
      - {{.Values.ingress.host }}
      {{- if .Values.ingress.customDomain }}
      - {{ .Values.ingress.customDomain }}
      {{- end }}
      secretName: odoo-tls
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /websocket
        pathType: Prefix
        backend:
          service:
            name: odoo-gevent
            port:
              number: 8072
      - path: /
        pathType: Prefix
        backend:
          service:
            name: odoo
            port:
              number: 8069
  {{- if .Values.ingress.customDomain }}
  - host: {{.Values.ingress.customDomain }}
    http:
      paths:
      - path: /websocket
        pathType: Prefix
        backend:
          service:
            name: odoo-gevent
            port:
              number: 8072
      - path: /
        pathType: Prefix
        backend:
          service:
            name: odoo
            port:
              number: 8069
  {{- end }}
{{- if and .Values.staging.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-{{ .Values.staging.name }}-ingress
  annotations:
    {{- if .Values.ingress.clusterIssuerRef }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuerRef }}
    {{- end }}
    {{- if eq .Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "128M"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.clusterIssuerRef }}
  tls:
    - hosts:
      - {{ .Values.staging.name }}.{{ .Values.ingress.host }}
      {{- if .Values.ingress.staging.customDomain }}
      - {{ .Values.ingress.staging.customDomain }}
      {{- end }}
      secretName: odoo-{{ .Values.staging.name }}-tls
  {{- end }}
  rules:
  - host: {{ .Values.staging.name }}.{{ .Values.ingress.host }}
    http:
      paths:
      - path: /websocket
        pathType: Prefix
        backend:
          service:
            name: odoo-{{ .Values.staging.name }}-gevent
            port:
              number: 8072
      - path: /
        pathType: Prefix
        backend:
          service:
            name: odoo-{{ .Values.staging.name }}
            port:
              number: 8069
  {{- if .Values.ingress.staging.customDomain }}
  - host: {{.Values.ingress.staging.customDomain }}
    http:
      paths:
      - path: /websocket
        pathType: Prefix
        backend:
          service:
            name: odoo-{{ .Values.staging.name }}-gevent
            port:
              number: 8072
      - path: /
        pathType: Prefix
        backend:
          service:
            name: odoo-{{ .Values.staging.name }}
            port:
              number: 8069
  {{- end }}
{{- end }}
{{- end }}