{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vuepress-ingress
  annotations:
    {{- if .Values.ingress.clusterIssuerRef }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuerRef }}
    {{- end }}
spec:
  ingressClassName: {{.Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vuepress
            port:
              number: 80
  {{- if .Values.ingress.customDomain }}
  - host: {{.Values.ingress.customDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vuepress
            port:
              number: 80
  {{- end }}
  {{- if .Values.ingress.clusterIssuerRef }}
  tls:
    - hosts:
      - {{.Values.ingress.host }}
      {{- if .Values.ingress.customDomain }}
      - {{ .Values.ingress.customDomain }}
      {{- end }}
      secretName: vuepress-ingress-cert
  {{- end }}
{{- end }}
