apiVersion: v2
name:  prometheusAgent
description: Prometheus agent mode scraper for Kubernetes.
home: https://kubernetes.build
maintainers:
  - name: Mint System GmbH
    email: support@mint-system.ch
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-state-metrics
    version: "5.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-state-metrics.enabled
