## @section prometheusAgent parameters
## @param image The image for Prometheus
image: prom/prometheus:v2.54.1
## @param imagePullPolicy Pull policy for  Prometheus image
imagePullPolicy: Always
## @param replicas Number of replicas for the Prometheus agent deployment
replicas: 1
## @section Remote write configuration
## @param remoteWrite.url The remote write endpoint URL.
remoteWrite:
  url: "https://prometheus.example.com/api/v1/write"
## @skip scrapeConfigs Prometheus scrape configuration in YAML format
scrapeConfigs: |
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: kubernetes_pod_name

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_address_InternalIP]
        target_label: __address__
        replacement: ${1}:10250
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __metrics_path__
        replacement: /metrics
      - source_labels: [__meta_kubernetes_node_name]
        target_label: kubernetes_node
## @section Resources requests and limits
resources:
  requests:
    ## @param resources.requests.memory Memory request for the container
        memory: "64Mi"
    ## @param resources.requests.cpu CPU request for the container
        cpu: "250m"
  limits:
    ## @param resources.limits.memory Memory limit for the container
        memory: "128Mi"
    ## @param resources.limits.cpu CPU limit for the container
        cpu: "500m"