## @section prometheusAgent parameters
## @param image The image for Prometheus
image: prom/prometheus:v2.54.1
## @param imagePullPolicy Pull policy for  Prometheus image
imagePullPolicy: Always
## @param replicas Number of replicas for the Prometheus agent deployment
replicas: 1
## @section Remote write configuration
## @param remoteWrite.url The remote write endpoint URL.
remoteWrite:
  url: "https://prometheus.mint-system.ch/api/v1/write"
## @skip scrapeConfigs Prometheus scrape configuration in YAML format
scrapeConfigs: |
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: kubernetes_pod_name
  - job_name: 'kubernetes-nodes'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__meta_kubernetes_node_address_InternalIP]
        target_label: __address__
        replacement: ${1}:10250
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - source_labels: [__meta_kubernetes_node_name]
        target_label: kubernetes_node
      - target_label: __metrics_path__
        replacement: /metrics
  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__meta_kubernetes_node_address_InternalIP]
        target_label: __address__
        replacement: ${1}:10250
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - source_labels: [__meta_kubernetes_node_name]
        target_label: kubernetes_node
      - target_label: __metrics_path__
        replacement: /metrics/cadvisor
  - job_name: 'kubernetes-kube-state-metrics'
    kubernetes_sd_configs:
      - role: service
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: '.*-kube-state-metrics'
        action: keep
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        regex: 'kube-state-metrics'
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: "http"
        action: keep
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
        target_label: __tmp_prometheus_io_probe
        regex: "true"
        action: replace
      - target_label: __address__
        source_labels: [__address__]
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
        target_label: kubernetes_instance
## @section Resources requests and limits
resources:
  requests:
    ## @param resources.requests.memory Memory request for the container
    memory: "64Mi"
    ## @param resources.requests.cpu CPU request for the container
    cpu: "250m"
  limits:
    ## @param resources.limits.memory Memory limit for the container
    memory: "128Mi"
    ## @param resources.limits.cpu CPU limit for the container
    cpu: "500m"

## @section Kube-state-metrics configuration
## @param kube-state-metrics.enabled Enable kube-state-metrics as sub-chart
kube-state-metrics:
  enabled: true
  resources:
    requests:
      ## @param kube-state-metrics.resources.requests.memory Memory request for the container
      cpu: 10m
      ## @param kube-state-metrics.resources.requests.cpu CPU request for the container
      memory: 32Mi
    limits:
      ## @param kube-state-metrics.resources.limits.memory Memory limit for the container
      memory: 128Mi